#!/usr/bin/env bash

WEBSOCKET_REDIS_NAME="websocket-redis"
WEBSOCKET_NETWORK_NAME="websocket-network"

WEBSOCKET_DEVELOPMENT_SERVICE_NAME="websocket-go-development"
WEBSOCKET_DEVELOPMENT_PORT=3001

WEBSOCKET_PRODUCTION_SERVICE_NAME="websocket-go-production"
WEBSOCKET_PRODUCTION_PORT=3001
