FROM golang:1.9.2

RUN apt-get update -y --fix-missing && \
    apt-get upgrade -y;

RUN go get github.com/cortesi/modd/cmd/modd \
    && go get -u github.com/go-redis/redis \
    && go-wrapper download github.com/satori/go.uuid \
    && go-wrapper download github.com/gorilla/websocket \
    && go-wrapper download github.com/streadway/amqp;

WORKDIR /go/src/app

CMD modd
